recipt_project/home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns=[
    path('', views.index, name='index'),
]

recipt_project/inventry/urls.py
from django.urls import path
from . import views
app_name = 'inventry'
urlpatterns=[
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('profile/', views.profile, name='profile'),
    path('delete/<int:prod_index>/<str:prod_code>/', views.delet, name='dele'),
    path('edit_product/<int:prod_index>/<str:prod_code>/', views.edit_product, name='edit_product'),
    path('search_results/', views.search_view, name='search_view'),
    path('inventry_sort/<int:asc_decs>/<str:sort_by>/', views.inventry_sort, name='inventry_sort'),
    path('export_to_excel/',views.export_excel,name='export_excel'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),]

recipt_project/management/urls.py
from django.urls import path
from . import views
from.import tests
app_name = 'management'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_user/', views.add_user, name='add_user'),
    path('remove_user/<int:user_index>/<str:username>/', views.remove_user, name='remove_user'),  # Remove user URL
    path('edit_user/<int:user_index>/<str:username>/', views.edit_user, name='edit_user'),  # Edit user URL
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('search_user/', views.search_user, name='search_user'),
    path('profile/', views.profile, name='profile'),
    path('user_sort/<int:asc_decs>/<str:sort_by>/', views.user_sort, name='user_sort'),
    path('sales_report/',views.sales_report_view,name='sales_report'),
    path('customer_sort/<int:asc_decs>/<str:sort_by>/',views.customer_sort,name='customer_sort'),
    path('customer_search/', views.customer_search, name='customer_search'),
    path('customerdata/', views.customerdata, name='customerdata'),
    path('get_recipt/<str:code>/<str:table_name>/', views.get_recipt, name='get_recipt'),
    ]

recipt_project/recipt_app/urls.py
from django.urls import path
from . import views
from . import views_return
from . import test
app_name = 'recipt'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('new/<int:return_product>/', views.new_receipt, name='new_receipt'),
    path('delete/<int:id>/', views.dele, name='dele'),
    path('edit_product/<int:id>/', views.edit_product, name='edit_product'),
    path('edit_product_return/<int:id>/<str:recipt_code_buy>/', views_return.edit_product_return, name='edit_product_return'),
    path('edit_customer/<str:customer_name>/<str:customer_email>/', views.edit_customer, name='edit_customer'),
    path('sendmail/<int:new_recipt>', views.sendmail, name='sendmail'),
    path('sendmail_return/<int:new_recipt>', views_return.sendmail_return, name='sendmail_return'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('save-customer/<int:new_recipt>/', views.save_customer_recipt, name='save_customer'),
    path('return-product/', views_return.return_product, name='return_product'),
    path('save_customer_return/<int:new_recipt>/',views_return.save_customer_recipt_return,name='save_customer_return'),
    path('profile/',views.profile,name='profile')
]

recipt_project/recipt_project/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipt_app/',include("recipt_app.urls")),
    path('inventry/',include("inventry.urls")),
    path('management/',include("management.urls")),
    path('',include("home.urls")),
]

recipt_project/management/views.py
from django.contrib.auth import authenticate, login, logout
from . import views_forms
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from . import models
from django.contrib.auth.hashers import check_password
import pandas as pd
from .sales_report import generate_report

def index(request):
    if not request.user.is_authenticated or models.select_userdata(request.user.username)[1] != "administration manager":
        return HttpResponseRedirect(reverse("management:login"))

    users = User.objects.all()
    databasedata=models.select_alluserdata()
    return render(request, 'management/index.html', {
        "databasedata":databasedata,
        "users": users,
        'length_users': len(users)
    })
def add_user(request):
    if not request.user.is_authenticated or models.select_userdata(request.user.username)[1] != "administration manager":
        return HttpResponseRedirect(reverse("management:login"))

    if request.method == 'POST':
        form = views_forms.NewDataForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            cnic = form.cleaned_data['cnic']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            address = form.cleaned_data['address']
            user_type = form.cleaned_data['user_type']
            
            password=form.cleaned_data['password']
            confirm_password=form.cleaned_data['confirm_password']
            try:
                # Create the user
                if(password==confirm_password):
                    user = User.objects.create_user(
                        username=username,
                        first_name=first_name,
                        last_name=last_name,
                        email=email,
                        password=password  # For demo; ideally generate/send password securely
                    )
                    
                    models.save_userdata(username,cnic,phone_number,address,user_type)
                    user.save()

                    messages.success(request, 'User created successfully!')
                else:
                    # messages.error(request, 'Passwords do not match!')
                    return render(request, 'management/error.html', {
                    "error": "Passwords do not match!"
                    })
                # Redirect to the index page
                # return redirect(reverse("management:index"))
            except Exception as e:
                # messages.error(request, f'Error creating user: {str(e)}')
                return render(request, 'management/error.html', {
                    "error": "Passwords do not match!"
                    })
        else:
            messages.error(request, 'Please correct the errors below.')
            return render(request, 'management/add.html', {'form': form})

    return render(request, 'management/add.html', {"form": views_forms.NewDataForm()})
def edit_user(request, user_index, username):
    if not request.user.is_authenticated or models.select_userdata(request.user.username)[1] != "administration manager":
        return HttpResponseRedirect(reverse("management:login"))
    
    user = User.objects.get(username=username)
    user_data = models.select_userdata(username)  # Assuming this function retrieves user data including cnic, phone_number, user_type, etc.
    if request.method == 'POST':
        form = views_forms.NewDataForm_edit(request.POST)
        try:
            if form.is_valid():
                user.username=username
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.email = form.cleaned_data['email']
                password=form.cleaned_data['password']
                confirm_password=form.cleaned_data['confirm_password']
                cnic = form.cleaned_data['cnic']
                phone_number = form.cleaned_data['phone_number']
                address = form.cleaned_data['address']
                user_type = form.cleaned_data['user_type']
                models.save_userdata(username, cnic, phone_number, address, user_type)  # Update User and custom Employ model
                if ((password or confirm_password) and (password==confirm_password)):
                    user.set_password(password)
                elif ((password or confirm_password) and (password!=confirm_password)):
                    return render(request, 'management/error.html', {
                        "error": "password and confirm password miss matches."
                        })
                user.save()
                messages.success(request, 'User updated successfully!')
                return redirect('management:index')
        except Exception as e:
                # messages.error(request, 'Please correct the errors below.')
                return render(request, 'management/error.html', {
                        "error": f"Please correct the errors . {e}"
                        })
    else:
        if not user_data:
            form = views_forms.NewDataForm_edit(initial={
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email,
            'username': user.username
        })
        else:
            form = views_forms.NewDataForm_edit(initial={
                'first_name': user.first_name,
                'last_name': user.last_name,
                'email': user.email,
                'username': user.username,
                'cnic': user_data[2],  # Assuming cnic is the 3rd column
                'phone_number': user_data[3],  # Assuming phone_number is the 4th column
                'user_type': user_data[1],  # Assuming user_type is the 2nd column
                'address': user_data[5],  # Assuming address is the 5th column
            })
    return render(request, 'management/add.html', {
        "form": form,
        'is_editing': True,
        'user_index': user_index,
        'username': username  # Fixed typo: 'usename' -> 'username'
    })
def remove_user(request, user_index,username):
    if not request.user.is_authenticated or models.select_userdata(request.user.username)[1] != "administration manager":
        return HttpResponseRedirect(reverse("management:login"))

    try:
        user = User.objects.get(username=username)
        user = User.objects.get(username=username)
        models.delete_userdata(username)
        user.delete()
        messages.success(request, f"User '{username}' has been deleted.")
        
    except User.DoesNotExist:
        # messages.error(request, f"User '{username}' not found.")
        return render(request, 'management/error.html', {
                    "error": f"User '{username}' not found."
                    })
    
    return redirect('management:index')

def profile(request):
    if not request.user.is_authenticated or models.select_userdata(request.user.username)[1] != "administration manager":
        return HttpResponseRedirect(reverse("management:login"))
    if request.method == 'POST':
        form = views_forms.ChangePasswordForm(request.POST)
        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['new_password']
            confirm_new_password = form.cleaned_data['confirm_new_password']

            # Validate old password against the user's current password
            if not check_password(old_password, request.user.password):
                return render(request, 'management/error.html', {
                        "error": "Your old password not correct."
                        })
            if confirm_new_password == new_password:
                # Save the new password
                request.user.set_password(new_password)
                request.user.save()
                return redirect('management:logout')
            else:
                return render(request, 'management/error.html', {
                        "error": "New password and confirm password do not match."
                        })
        else:
            return render(request, 'management/profile.html', {
                "form": form,
                "user_data": models.select_userdata(request.user.username),
                "django_userdata": [request.user.first_name, request.user.last_name, request.user.email],
            })

    form = views_forms.ChangePasswordForm()
    django_userdata = [request.user.first_name, request.user.last_name, request.user.email]
    return render(request, 'management/profile.html', {
        "form": form,
        "user_data": models.select_userdata(request.user.username),
        "django_userdata": django_userdata,
    })

def search_user(request):
    if not request.user.is_authenticated or models.select_userdata(request.user.username)[1] != "administration manager":
        return HttpResponseRedirect(reverse("management:login"))
    search_column = request.GET.get('section', 'username')  # Default search column
    search_value = request.GET.get('q', '')  # Retrieved search value
    
    # Convert search_value to string (if not already a string)
    search_value = str(search_value)
    results = []  # Initialize results list

    # Check if search_value is not empty
    if search_value:
        results = models.search_user(search_column, search_value)
        databasedata , users =arange_user(results)
    # Render the template with search results
    return render(request, 'management/index.html', {
        "databasedata":databasedata,
        "users": users,
        'length_user': range(len(results))
    })

recipt_project/management/templates/management/customer_table.html
{% extends "management/layout.html" %}

{% block body %}
<div>
    <div class="search-bar-container">
        <input type="text" id="searchInput" required placeholder="Search...">
        <select id="searchSection" required onchange="autoSearch()">
            <option value="" disabled selected>Search by</option>
            <option value="name">Name</option>
            <option value="email">Email</option>
            <option value="Employ_name">Employ name</option>
            <option value="recipt_code_buy">recipt code buy</option>
            <option value="recipt_code_return">recipt code return</option>
            <option value="total_price">total price</option>
            <option value="date_time">date time</option>
            <option value="all">All </option>
        </select>
        <a href="{% url 'management:sales_report'%}">
            <button type="button" style="background-color: brown; color: white; padding: 5px;margin-left: 30px; border-radius: 5px;"><strong>SALES REPORT</strong></button>
        </a>
    </div>
</div>
<div id="index_outer_div" class="user-details">
    {% if customer_buy or customer_return %}
    <table class="user-table">
        <thead>
            <tr>
                <th>index no</th>
                <th>{% if sorted_as == '0Name' %}
                    <a href="{% url 'management:customer_sort' 1 'Name' %}" class="hover-effect">
                        <h3>Name</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:customer_sort' 0 'Name' %}" class="hover-effect">
                        <h3>Name</h3>
                    </a>
                    {% endif %}
                </th>
                <th>{% if sorted_as == '0email' %}
                    <a href="{% url 'management:customer_sort' 1 'email' %}" class="hover-effect">
                        <h3>Email</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:customer_sort' 0 'email' %}" class="hover-effect">
                        <h3>Email</h3>
                    </a>
                    {% endif %}
                </th>
                <th>{% if sorted_as == '0Employ_name' %}
                    <a href="{% url 'management:customer_sort' 1 'Employ_name' %}" class="hover-effect">
                        <h3>Employ name</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:customer_sort' 0 'Employ_name' %}" class="hover-effect">
                        <h3>Employ name</h3>
                    </a>
                    {% endif %}
                </th>
                <th>{% if sorted_as == '0recipt_code' %}
                    <a href="{% url 'management:customer_sort' 1 'recipt_code' %}" class="hover-effect">
                        <h3>recipt code buy</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:customer_sort' 0 'recipt_code' %}" class="hover-effect">
                        <h3>recipt code buy</h3>
                    </a>
                    {% endif %}
                </th>
                <th><h3>recipt code return</h3></th>
                <th>{% if sorted_as == '0total_price' %}
                    <a href="{% url 'management:customer_sort' 1 'total_price' %}" class="hover-effect">
                        <h3>total price</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:customer_sort' 0 'total_price' %}" class="hover-effect">
                        <h3>total price</h3>
                    </a>
                    {% endif %}
                </th>

                <th>{% if sorted_as == '0date_time' %}
                    <a href="{% url 'management:customer_sort' 1 'date_time' %}" class="hover-effect">
                        <h3>Date time</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:customer_sort' 0 'date_time' %}" class="hover-effect">
                        <h3>Date time</h3>
                    </a>
                    {% endif %}
                </th>
            </tr>
        </thead>
        <tbody>
            {% for cust_buy in customer_buy %}
            <tr>
                <td>{{ forloop.counter0 }}</td>
                <td>{{ cust_buy.1 }}</td>
                <td>{{ cust_buy.2 }}</td>
                <td>{{ cust_buy.3 }}</td>
                <td><a href="{% url 'management:get_recipt' cust_buy.4 'customers' %}" class="hover-effect">{{ cust_buy.4 }}</a></td>
                <td>NONE</td>
                <td>{{cust_buy.5}}</td>
                <td>{{ cust_buy.6 }}</td>
            </tr>
                {% for cust_return in customer_return %}
                {% if cust_return.4 == cust_buy.4 %}
            <tr style="color: rgb(110, 0, 0);">
                <td>{{ cust_return.0 }}</td>
                <td>{{ cust_return.1 }}</td>
                <td>{{ cust_return.2 }}</td>
                <td>{{ cust_return.3 }}</td>
                <td><a href="{% url 'management:get_recipt' cust_return.4 'customers' %}" class="hover-effect">{{ cust_return.4 }}</a></td>
                <td><a href="{% url 'management:get_recipt' cust_return.5 'customers_return' %}" class="hover-effect">{{ cust_return.5 }}</a></td>
                <td>{{ cust_return.6 }}</td>
                <td>{{ cust_return.7 }}</td>
            </tr>
                {% endif %}
                {% endfor %}
            
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h1>No users added</h1>
    {% endif %}
</div>

<script>
    const searchUrl = "{% url 'management:customer_search'%}";
    function autoSearch() {
        const query = document.getElementById('searchInput').value;
        const section = document.getElementById('searchSection').value;

        if (!query.trim()) {
            alert("Please enter a search query.");
            return;
        }

        if (!section) {
            alert("Please select a section to search.");
            return;
        }

        window.location.href = `${searchUrl}?q=${encodeURIComponent(query)}&section=${encodeURIComponent(section)}`;
    }

    document.getElementById('searchInput').addEventListener('keypress', function (event) {
        if (event.key === 'Enter') {
            autoSearch();
        }
    });
</script>
{% endblock %}

recipt_project/management/templates/management/index.html
{% extends "management/layout.html" %}

{% block body %}
<div>
    <div class="search-bar-container">
        <input type="text" id="searchInput" required placeholder="Search...">
        <select id="searchSection" required onchange="autoSearch()">
            <option value="" disabled selected>Search by</option>
            <option value="username">Username</option>
            <option value="first_name">First Name</option>
            <option value="last_name">Last Name</option>
            <option value="email">Email</option>
            <option value="user_type">user type</option>
            <option value="cnic">CNIC</option>
            <option value="updated_datetime">date joined / Updated</option>
            <option value="phone_number">Phone Number</option>
            <option value="address">Address</option>
            <option value="all">All Users</option>
        </select>
        <div class="actions">
            <a href="{% url 'management:add_user' %}" class="action-button"><button style="background-color: brown; color: white; padding: 5px;margin-left: 30px; border-radius: 5px;"><strong>Add New Employ</strong></button></a>
        </div>
        {% if error_message %}
            <div class="alert alert-danger">{{ error_message }}</div>
        {% endif %}
    </div>
</div>
<div id="index_outer_div" class="user-details">
    {% if users %}
    <table class="user-table">
        <thead>
            <tr>
                <th>index no</th>
                <th><a href="{% url 'management:index' %}" class="hover-effect">Username</a>
                </th>
                <th>{% if sorted_as == '0first_name' %}
                    <a href="{% url 'management:user_sort' 1 'first_name' %}" class="hover-effect">
                        <h3>First Name</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:user_sort' 0 'first_name' %}" class="hover-effect">
                        <h3>First Name</h3>
                    </a>
                    {% endif %}
                </th>
                <th>{% if sorted_as == '0last_name' %}
                    <a href="{% url 'management:user_sort' 1 'last_name' %}" class="hover-effect">
                        <h3>Last Name</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:user_sort' 0 'last_name' %}" class="hover-effect">
                        <h3>Last Name</h3>
                    </a>
                    {% endif %}
                </th>
                <th>{% if sorted_as == '0email' %}
                    <a href="{% url 'management:user_sort' 1 'email' %}" class="hover-effect">
                        <h3>Email</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:user_sort' 0 'email' %}" class="hover-effect">
                        <h3>Email</h3>
                    </a>
                    {% endif %}
                </th>
                <th>{% if sorted_as == '0user_type' %}
                    <a href="{% url 'management:user_sort' 1 'user_type' %}" class="hover-effect">
                        <h3>User Type</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:user_sort' 0 'user_type' %}" class="hover-effect">
                        <h3>User Type</h3>
                    </a>
                    {% endif %}
                </th>
                <th>{% if sorted_as == '0cnic' %}
                    <a href="{% url 'management:user_sort' 1 'cnic' %}" class="hover-effect">
                        <h3>CNIC</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:user_sort' 0 'cnic' %}" class="hover-effect">
                        <h3>CNIC</h3>
                    </a>
                    {% endif %}
                </th>
                <th>{% if sorted_as == '0phone_number' %}
                    <a href="{% url 'management:user_sort' 1 'phone_number' %}" class="hover-effect">
                        <h3>Phone N0</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:user_sort' 0 'phone_number' %}" class="hover-effect">
                        <h3>Phone N0</h3>
                    </a>
                    {% endif %}
                </th>
                <th>{% if sorted_as == '0updated_datetime' %}
                    <a href="{% url 'management:user_sort' 1 'updated_datetime' %}" class="hover-effect">
                        <h3>Date joined</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:user_sort' 0 'updated_datetime' %}" class="hover-effect">
                        <h3>Date joined</h3>
                    </a>
                    {% endif %}
                </th>
                <th>{% if sorted_as == '0address' %}
                    <a href="{% url 'management:user_sort' 1 'address' %}" class="hover-effect">
                        <h3>Address</h3>
                    </a>
                    {% else %}
                    <a href="{% url 'management:user_sort' 0 'address' %}" class="hover-effect">
                        <h3>Address</h3>
                    </a>
                    {% endif %}
                </th>

                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ forloop.counter0 }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.email }}</td>
                {% for userdata in databasedata %}
                    {% if userdata.0 == user.username %}
                        <td>{{ userdata.1 }}</td>
                        <td>{{ userdata.2 }}</td>
                        <td>{{ userdata.3 }}</td>
                        <td>{{ userdata.4 }}</td>
                        <td>
                            <span class="address-preview" title="{{ userdata.5 }}">
                                {{ userdata.5|slice:":9" }}
                            </span>
                        </td>
                        
                    {% endif %}
                {% endfor %}
                <td>
                    {% load static %}
                    {% if request.user.username != user.username %}
                    <a href="{% url 'management:remove_user' forloop.counter0 user.username %}" class="delete-button">
                        <img src="{% static 'management_css/assets/delete_icon.jpg' %}" alt="Delete" style="width: 17px; height: 23px;">
                    </a>
                    {% else %}
                        <div style="width: 17px; height: 23px;display: inline-flex;" ></div>
                    {% endif %}
                    <a href="{% url 'management:edit_user' forloop.counter0 user.username %}" class="edit-button">
                        <img src="{% static 'management_css/assets/edit_icon.jpeg' %}" alt="Edit" style="width: 17px; height: 23px;">
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <h1>No users added</h1>
    {% endif %}
</div>

<script>
    const searchUrl = "{% url 'management:search_user' %}";
    function autoSearch() {
        const query = document.getElementById('searchInput').value;
        const section = document.getElementById('searchSection').value;

        if (!query.trim()) {
            alert("Please enter a search query.");
            return;
        }

        if (!section) {
            alert("Please select a section to search.");
            return;
        }

        window.location.href = `${searchUrl}?q=${encodeURIComponent(query)}&section=${encodeURIComponent(section)}`;
    }

    document.getElementById('searchInput').addEventListener('keypress', function (event) {
        if (event.key === 'Enter') {
            autoSearch();
        }
    });
</script>

{% endblock %}

recipt_project/management/templates/management/layout.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'management_css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'management_css/assets/EZ logo.jpg' %}" alt="EZ MART">
    <title>EZ MART</title>
</head>
<body>
    <header>
        <div class="header-left">
            <div>
            <a href="{% url 'recipt:index' %}" target="_blank">
                <button type="button" class="logout-button">Counter</button>
            </a>
            <a href="{% url 'inventry:index' %}" target="_blank">
                <button type="button" class="logout-button">Inventroy</button>
            </a>
        </div>
        <div>
            <a href="{% url 'management:index' %}" target="_blank">
                <button type="button" class="logout-button">Management</button>
            </a>
            <a href="{% url 'management:customerdata' %}" target="_blank">
                <button type="button" class="logout-button">Sales Data</button>
            </a>
        </div>
        </div>

        <div class="header-center">
            <div class="header-title">Easy Mart</div>
            <div class="section-title">Management Section</div>
        </div>

        <div class="header-right">
            <a href="{% url 'management:logout' %}">
                <button type="button" class="logout-button">Log out</button>
            </a>
            <a href="{% url 'management:profile' %}">
                <button type="button" class="logout-button">Profile</button>
            </a>
        </div>
    </header>
    <div id="outerContainer">
        <div id="container">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>

</html>