recipt_project/home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns=[
    path('', views.index, name='index'),
]

recipt_project/recipt_app/urls.py
from django.urls import path
from . import views
from . import views_return
from . import test
app_name = 'recipt'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('new/<int:return_product>/', views.new_receipt, name='new_receipt'),
    path('delete/<int:id>/', views.dele, name='dele'),
    path('edit_product/<int:id>/', views.edit_product, name='edit_product'),
    path('edit_product_return/<int:id>/<str:recipt_code_buy>/', views_return.edit_product_return, name='edit_product_return'),
    path('edit_customer/<str:customer_name>/<str:customer_email>/', views.edit_customer, name='edit_customer'),
    path('sendmail/<int:new_recipt>', views.sendmail, name='sendmail'),
    path('sendmail_return/<int:new_recipt>', views_return.sendmail_return, name='sendmail_return'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('save-customer/<int:new_recipt>/', views.save_customer_recipt, name='save_customer'),
    path('return-product/', views_return.return_product, name='return_product'),
    path('save_customer_return/<int:new_recipt>/',views_return.save_customer_recipt_return,name='save_customer_return'),
    path('profile/',views.profile,name='profile')
]

recipt_project/recipt_project/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipt_app/',include("recipt_app.urls")),
    path('inventry/',include("inventry.urls")),
    path('management/',include("management.urls")),
    path('',include("home.urls")),
]

recipt_project/recipt_app/views.py
from django.contrib.auth import authenticate, login, logout
from . import views_forms
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from datetime import datetime
from .sendmail import sendmail_py
import random
import string
from django.views.decorators.csrf import csrf_exempt
from . import models  # Assuming this function saves customer data to DB
from django.contrib import messages
from django.contrib.auth.hashers import check_password

# Helper function to generate a random receipt number
def generate_random_key(length=5):
    characters = string.ascii_lowercase + string.digits  # Only lowercase letters and digits
    random_key = ''.join(random.choices(characters, k=length))
    return "_" + random_key

def index(request):
    if not request.user.is_authenticated or ((models.select_userdata(request.user.username)[1] != "counter manager" and models.select_userdata(request.user.username)[1] != "administration manager")):
        return HttpResponseRedirect(reverse("recipt:login"))

    # Initialize session variables if they do not exist
    if "products" not in request.session:
        request.session["products"] = []

    if "total_price" not in request.session:
        request.session["total_price"] = 0
    if "customer_name" not in request.session:
        request.session["customer_name"] = None
    if "customer_email" not in request.session:
        request.session["customer_email"] = None
    if "recipt_code_buy" not in request.session:
        request.session["recipt_code_buy"] = None
    if "recipt_code" not in request.session:
        request.session["recipt_code"] = generate_random_key()

    return render(request, 'recipt/index.html', {
        "products": request.session["products"],
        "total_price": request.session["total_price"],
        "customer_name": request.session["customer_name"],
        "customer_email": request.session["customer_email"],
        'range_5': range(len(request.session["products"])),
        'now': datetime.now(),
        'recipt_code': request.session["recipt_code"],
        'recipt_code_buy':request.session["recipt_code_buy"]
    })
# View to send email and handle success/error scenarios
def sendmail(request, new_recipt):
    if not request.user.is_authenticated or ((models.select_userdata(request.user.username)[1] != "counter manager" and models.select_userdata(request.user.username)[1] != "administration manager")):
        return HttpResponseRedirect(reverse("recipt:login"))

    # Retrieve user and session data
    user_data = {
        'username': request.user.username,
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
        'products': request.session.get("products"),
        'total_price': request.session.get("total_price"),
        'customer_name': request.session.get("customer_name"),
        'customer_email': request.session.get("customer_email"),
        'recipt_code': request.session.get("recipt_code")
    }

    # Ensure session data exists
    if not user_data['products'] :
        return render(request, 'recipt/error.html', {
                        "error": f"Required session data is missing. product is {user_data['products']}"
                        })
    if not user_data['customer_name'] :
        return render(request, 'recipt/error.html', {
                        "error": f"Required session data is missing. customer name is {user_data['customer_name']}"
                        })
    if not user_data['customer_email']:
        return render(request, 'recipt/error.html', {
                        "error": f"Required session data is missing. customer email is {user_data['customer_email']}"
                        })
    # Send email and handle response from sendmail_py
    result = sendmail_py(user_data)

    if result.startswith("Error"):
        # Redirect to edit_customer with the customer's name and email as URL parameters
        return redirect('recipt:edit_customer', customer_name=user_data['customer_name'], customer_email=user_data['customer_email'])

    elif result == "Success":
        # Save customer data before sending email
        return save_customer_recipt(request, new_recipt)

    else:
        return render(request, 'recipt/error.html', {
                        "error": f"An unexpected issue occurred while sending the email. to {user_data['customer_name']} on {user_data['customer_email']}."
                        })

    # Catch-all return, ensuring we never return None
    return HttpResponse("Unexpected error.", status=500)
# View to add new product and customer data to session
def add(request):
    if not request.user.is_authenticated or ((models.select_userdata(request.user.username)[1] != "counter manager" and models.select_userdata(request.user.username)[1] != "administration manager")):
        return HttpResponseRedirect(reverse("recipt:login"))
    
    if request.method == 'POST':
        form_product = views_forms.ProductForm(request.POST)
        form_customer = views_forms.CustomerForm(request.POST)
        if form_product.is_valid() and form_customer.is_valid():
            prod_code = form_product.cleaned_data['prod_code']
            quantity = form_product.cleaned_data['quantity']
            product_recipt = models.get_product(prod_code)
            if product_recipt:
                if product_recipt[2] >= quantity:
                    quantity_price = product_recipt[3] * quantity
                    product_found = False

                    for product in request.session["products"]:
                        if product[0] == prod_code:
                            product[1] += quantity
                            product[3] += quantity_price
                            product_found = True
                            break

                    if not product_found:
                        request.session["products"].append([prod_code, quantity, product_recipt[3], quantity_price,product_recipt[1]])
                    request.session['total_price'] += quantity_price
                else:
                    return render(request, 'recipt/error.html', {
                        "error": f"product quantity not available ({product_recipt[2]})"
                        })
            else:
                return render(request, 'recipt/error.html', {
                        "error": "product code not available"
                        })
            customer_name = form_customer.cleaned_data['customer_name']
            customer_email = form_customer.cleaned_data['customer_email']
            if customer_name:
                request.session["customer_name"] = customer_name
            if customer_email:
                request.session["customer_email"] = customer_email

        else:
            return render(request, 'recipt/add.html', {'form_product': form_product, 'form_customer': form_customer})
    return render(request, 'recipt/add.html', {"form_product": views_forms.ProductForm(), 'form_customer': views_forms.CustomerForm()})
# View to start a new receipt
def new_receipt(request,return_product=0):
    if not request.user.is_authenticated or ((models.select_userdata(request.user.username)[1] != "counter manager" and models.select_userdata(request.user.username)[1] != "administration manager")):
        return HttpResponseRedirect(reverse("recipt:login"))

    # Reset session data for a new receipt
    request.session["products"] = []
    request.session["total_price"] = 0
    request.session["recipt_code_buy"]=None
    request.session["customer_name"] = None
    request.session["customer_email"] = None
    request.session["recipt_code"] = generate_random_key()
    if return_product:
        return redirect('recipt:return_product')
    else:
        return redirect('recipt:add')
# View to delete a product from the session
def dele(request, id):
    if not request.user.is_authenticated or ((models.select_userdata(request.user.username)[1] != "counter manager" and models.select_userdata(request.user.username)[1] != "administration manager")):
        return HttpResponseRedirect(reverse("recipt:login"))

    try:
        product = request.session["products"].pop(id)
        request.session['total_price'] -= product[3]  # Subtract the quantity_price
    except IndexError:
        return render(request, 'recipt/error.html', {
                        "error": f"Invalid index :: {IndexError}"
                        })# Handle index errors if necessary

    return redirect('recipt:index')
# View to edit customer details
def edit_customer(request, customer_name=None, customer_email=None):
    if not request.user.is_authenticated or ((models.select_userdata(request.user.username)[1] != "counter manager" and models.select_userdata(request.user.username)[1] != "administration manager")):
        return HttpResponseRedirect(reverse("recipt:login"))

    if request.method == 'POST':
        customer_form = views_forms.CustomerForm(request.POST)
        if customer_form.is_valid():
            customer_name = customer_form.cleaned_data['customer_name']
            customer_email = customer_form.cleaned_data['customer_email']
            request.session['customer_name'] = customer_name
            request.session['customer_email'] = customer_email
            return redirect('recipt:index')
    else:
        customer_form = views_forms.CustomerForm(initial={'customer_name': customer_name, 'customer_email': customer_email})
    return render(request, 'recipt/edit_customer.html', {"customer_form": customer_form, "customer_name": customer_name, "customer_email": customer_email})

# View to edit product details
def edit_product(request, id):

recipt_project/recipt_app/templates/recipt/add.html
{% extends "recipt/layout.html" %}

{% block body %}
<div>
    <form
    action="{% if is_editing %}{% url 'recipt:edit_product' id %} 
    {% elif is_editing_return %} {% url 'recipt:edit_product_return' id recipt_code_buy %} 
    {% else %}{% url 'recipt:add' %}{% endif %}" 
    method="post">
        {% csrf_token %}
        <!-- Dynamic heading based on whether you are adding or editing an item -->
        <h1>
            {% if is_editing %}
                Please edit details
            {% else %}
                Please add details
            {% endif %}
        </h1>
        
        {% if not request.session.customer_name %}
            <!-- Show the customer name field only if it is not already set -->
            {% if form_customer %}
                {{ form_customer.as_p }}
            {% endif %}
        {% endif %}
        
        {% if form_product %}
            {{ form_product.as_p }}
        {% endif %}
        
        <input type="submit" style="width: fit-content; height: fit-content; background-color: brown; color: white; padding: 5px; margin-top: 7px; border-radius: 2px; border: 1px solid rgb(0, 0, 0);">
    </form>

    <a href="{% url 'recipt:index' %}">
        <button style="width: fit-content; height: fit-content; background-color: brown; color: white; padding: 5px; margin-top: -25px; border-radius: 2px; border: 1px solid rgb(0, 0, 0); float: right;">
            Your receipt
        </button>
    </a>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        // Focus on the product name field if the customer name field is hidden
        const productNameField = document.getElementById("id_name");
        const customerNameField = document.getElementById("id_customer_name");

        if (customerNameField && !customerNameField.closest("form").querySelector(".hidden")) {
            // Focus on the customer name field if it's visible
            customerNameField.focus();
        } else if (productNameField) {
            // Focus on the product name field otherwise
            productNameField.focus();
        }
    });
</script>
{% endblock %}

recipt_project/recipt_app/templates/recipt/edit_customer.html
{% extends "recipt/layout.html" %}

{% block body %}
<div>
    <form action="{% url 'recipt:edit_customer' customer_name customer_email %}" method="post">
        {% csrf_token %}
        <h1>Edit Customer Details</h1>
        {% if customer_form %}
        {{ customer_form }}
        {% endif %}
        <input type="submit" value="Update Details" style="background-color: brown; color: white; padding: 5px; margin-top: 30px;">
    </form>

    <a href="{% url 'recipt:index' %}">
        <button style="background-color: brown; color: white; padding: 5px; float: right; margin-top: -25px;">
            Back to Receipt
        </button>
    </a>
</div>
{% endblock %}

recipt_project/recipt_app/templates/recipt/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redirecting</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            background-color: #f8f9fa;
            color: #333;
        }
        .container {
            text-align: center;
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 30px;
            background-color: #fff;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 90%;
        }
        .message {
            font-size: 18px;
            margin-bottom: 20px;
            color: #555;
        }
        .error {
            color: #d9534f;
            font-weight: bold;
            margin-bottom: 20px;
        }
        h1 {
            font-size: 24px;
            margin-bottom: 10px;
        }
        button {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
    <script type="text/javascript">
        function action() {
            // Go back to the previous page immediately when the button is clicked
            window.history.back();
        }

        // Listen for the "Enter" key press
        document.addEventListener("keydown", function(event) {
            if (event.key === "Enter") {
                action(); // Trigger the action if "Enter" is pressed
            }
        });
    </script>
</head>
<body>
    <div class="container">
        <h1>An Exception Occurred</h1>
        <h2 class="error">{{ error }}</h2>
        <p class="message">Please check the issue and try again.</p>
        <button onclick="action()">OK, Go Back</button>
    </div>
</body>
</html>

recipt_project/recipt_app/templates/recipt/index.html
{% extends "recipt/layout.html" %}

{% block body %}
<style>
    /* Table Styling */
.product-table {
  width: 100%;
  border-collapse: collapse; /* Remove gaps between cells */
  border-radius: 10px; /* Apply border radius to the table */
  overflow: hidden; /* Ensure the border radius effect is visible */
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2); /* Add shadow to the table */
}

.product-table th, .product-table td {
  padding: 10px; /* Add padding for better spacing */
  text-align: left; /* Align text to the left */
}

/* Alternating Row Colors */
.product-table tbody tr:nth-child(even) {
  background-color: #e8e8e8; /* Light gray for even rows */
}

.product-table tbody tr:nth-child(odd) {
  background-color: #ffffff; /* White for odd rows */
}

/* Optional: Highlight on hover */
.product-table tbody tr:hover {
  background-color: rgb(173, 173, 173); /* Light blue on hover */
}
.product-table thead tr{
  background-color: brown;
  /* color:#ffffff */
}

.product-table thead tr th:hover {
  font-weight:bolder;
}


</style>

<div>
    <div id="receipt-content">
        <div style="display: flex; justify-content: space-between;">
            <div>
                {% if not customer_name %}
                    {% if request.user.first_name and request.user.last_name %}
                        <h3>Here is your receipt by {{ request.user.first_name }} {{ request.user.last_name }}
                        <a href="{% url 'recipt:edit_customer' customer_name customer_email %}" class="edit-button">
                            <img src="https://th.bing.com/th/id/OIP.P6trHImFdjGgSXQBU7_sagHaHa?rs=1&pid=ImgDetMain"
                                alt="EDIT" style="width: 15px; height: 20px;  margin-right: 10px;">
                        </a></h3>
                        {% else %}
                        <h3>Here is your receipt by {{ request.user.username }}
                        <a href="{% url 'recipt:edit_customer' customer_name customer_email %}" class="edit-button">
                            <img src="https://th.bing.com/th/id/OIP.P6trHImFdjGgSXQBU7_sagHaHa?rs=1&pid=ImgDetMain"
                                alt="EDIT" style="width: 15px; height: 20px;  margin-right: 10px;">
                        </a></h3>
                    {% endif %}
                {% else %}
                    {% if request.user.first_name and request.user.last_name %}
                        <h3>Here is {{ customer_name }}'s receipt by {{ request.user.first_name }} {{ request.user.last_name }}
                            {% if customer_name %}
                                <a href="{% url 'recipt:edit_customer' customer_name customer_email %}" class="edit-button">
                                    <img src="https://th.bing.com/th/id/OIP.P6trHImFdjGgSXQBU7_sagHaHa?rs=1&pid=ImgDetMain"
                                        alt="EDIT" style="width: 15px; height: 20px;  margin-right: 10px;">
                                </a>
                        {% endif %}
                        </h3>
                    {% else %}
                        <h3>Here is {{ customer_name }}'s receipt by {{ request.user.username }}
                            {% if customer_name %}
                                <a href="{% url 'recipt:edit_customer' customer_name customer_email %}" class="edit-button">
                                    <img src="https://th.bing.com/th/id/OIP.P6trHImFdjGgSXQBU7_sagHaHa?rs=1&pid=ImgDetMain"
                                        alt="EDIT" style="width: 15px; height: 20px;  margin-right: 10px;">
                                </a>
                            {% endif %}
                        </h3>
                    {% endif %}
                {% endif %}
            </div>
            <h6 class="receipt-date">{{ now }}</h6>
        </div>
        {% if products %}
        {% if recipt_code or recipt_code_buy %}
        <h6>
            {% if recipt_code %}recipt code: {{ recipt_code }}{% endif %}
            {% if recipt_code and recipt_code_buy %} | {% endif %}
            {% if recipt_code_buy %}recipt buy code: {{ recipt_code_buy }}{% endif %}
        </h6>
        {% endif %}
        {% endif %}

        <div id="index_outer_div" class="receipt-details">
            {% if products %}
            <table class="product-table">
                <thead>
                    <tr>
                        <th>Index No</th>
                        <th>Product Name</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Total for Each Item</th>
                        <th>Description</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                    <tr>
                        <td>{{ forloop.counter0 }}</td>
                        <td>{{ product.0 }}</td>
                        <td>{{ product.1 }}</td>
                        <td>{{ product.2 }}</td>
                        <td>{{ product.3 }}</td>
                        <td>{{ product.4 }}</td>
                        <td>
                            {% load static %}
                            <a href="{% url 'recipt:dele' forloop.counter0 %}" class="delete-button">
                                <img src="{% static 'recipt_css/assets/delete_icon.jpg' %}" alt="Delete"
                                    style="width: 15px; height: 20px;">
                            </a>
                            {% if recipt_code_buy %}
                            <a href="{% url 'recipt:edit_product_return' forloop.counter0 recipt_code_buy %}"
                                class="edit-button">
                                <img src="{% static 'recipt_css/assets/edit_icon.jpeg' %}" alt="Edit"
                                    style="width: 15px; height: 20px;">
                            </a>
                            {% else %}
                            <a href="{% url 'recipt:edit_product' forloop.counter0 %}" class="edit-button">
                                <img src="{% static 'recipt_css/assets/edit_icon.jpeg' %}" alt="Edit"
                                    style="width: 15px; height: 20px;">
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <h1>No items added</h1>
            {% endif %}
        </div>

        <div>
            <h4>Total Price: {{ total_price }}</h4>
        </div>
        <br>
    </div>
    <div style="display: flex; flex-wrap: wrap; gap: 10px; justify-content: center; margin: 20px 0;">
        {% if not recipt_code_buy and products %}
        <a href="{% url 'recipt:add' %}" class="action-button">
            <button class="styled-button"><strong>Add New Product</strong></button>
        </a>
        <a href="{% url 'recipt:sendmail' 1 %}" class="action-button">
            <button class="styled-button"><strong>Send E-Receipt</strong></button>
        </a>
        <a href="{% url 'recipt:save_customer' 1 %}" class="action-button">
            <button class="styled-button"><strong>Save E-Receipt</strong></button>
        </a>
        {% endif %}
    
        {% if recipt_code_buy and products %}
        <a href="{% url 'recipt:return_product' %}" class="action-button">
            <button class="styled-button"><strong>Add Return Product</strong></button>
        </a>
        <a href="{% url 'recipt:sendmail_return' 1 %}" class="action-button">
            <button class="styled-button"><strong>Send Return E-Receipt</strong></button>
        </a>
        <a href="{% url 'recipt:save_customer_return' 1 %}" class="action-button">
            <button class="styled-button"><strong>Save Return E-Receipt</strong></button>
        </a>
        {% endif %}
    
        {% if products %}
        <button onclick="printAndSaveReceipt()" class="styled-button"><strong>Print</strong></button>
        {% endif %}
        <div>
        <a href="{% url 'recipt:new_receipt' 0 %}" class="action-button">
            <button class="styled-button"><strong>New Buy Receipt</strong></button>
        </a>
        <a href="{% url 'recipt:new_receipt' 1 %}" class="action-button">
            <button class="styled-button"><strong>New Return Product</strong></button>
        </a>
    </div>
    </div>
    
</div>
    <script>
        function printAndSaveReceipt() {
            document.querySelectorAll('.delete-button').forEach(el => el.style.display = 'none');
            document.querySelectorAll('.edit-button').forEach(el => el.style.display = 'none');

            window.print();

            document.querySelectorAll('.delete-button').forEach(el => el.style.display = 'inline');
            document.querySelectorAll('.edit-button').forEach(el => el.style.display = 'inline');

            console.log("Saving data after printing...");
            saveCustomer()
            // setTimeout(saveCustomer, 1000); // 1-second delay
        }

        function saveCustomer() {
            const xhr = new XMLHttpRequest();
            xhr.open("GET", "/recipt_app/save-customer/1", true);
            xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");

            xhr.onload = function () {
                if (xhr.status === 200) {
                    console.log("Customer data saved successfully!");
                    // Redirect to a new receipt after saving
                    window.location.href = "/recipt_app/new/1/";
                } else {
                    console.log("Error saving customer data: " + xhr.status);
                }
            };

            xhr.onerror = function () {
                console.log("Request failed.");
            };

            xhr.send();
        }
    </script>

    {% endblock %}

recipt_project/recipt_app/templates/recipt/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipt_css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'recipt_css/assets/EZ logo.jpg' %}" alt="EZ MART">
    <title>EZ MART</title>
</head>
<body>
    <header>
        <div class="header-center">
            <div class="header-title">Easy Mart</div>
            <div class="section-title">Counter Section</div>
        </div>
        <div class="header-right">
        <a href="{% url 'recipt:logout' %}">
            <button type="button" class="logout-button"><strong>Log out</strong></button>
        </a>
        <a href="{% url 'recipt:profile' %}">
            <button type="button" class="logout-button"><strong>profile</strong></button>
        </a>
        </div>
    </header>

    <div id="outerContainer">
        <div id="container">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

recipt_project/recipt_app/templates/recipt/redirect_popup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redirecting</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            background-color: #f8f9fa;
            color: #333;
        }
        .container {
            text-align: center;
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }
        .message {
            font-size: 18px;
            margin-bottom: 20px;
        }
        .error {
            color: red;
            margin-top: 10px;
        }
        h1 {
            font-size: 24px;
            margin: 20px 0;
        }
    </style>
    <script type="text/javascript">
        window.onload = function() {
            // Redirect after 3 seconds
            setTimeout(function() {
                window.location.href = "{% url 'recipt:new_receipt' 0 %}";
            }, 3000); // 3000 milliseconds = 3 seconds
        };
    </script>
</head>
<body>
    <div class="container">
        <h2 class="message">E-Receipt sent to {{ customer_name }} at {{ customer_email }}</h2>
        {% if error %}
        <p class="error">{{ error }}</p>
        {% endif %}
        <h1>Redirecting...</h1>
    </div>
</body>
</html>

recipt_project/recipt_app/templates/recipt/return_product.html
{% extends "recipt/layout.html" %}

{% block body %}
{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %}

<div>
    <form action="{% if is_editing %}{% url 'recipt:edit_product' id %}{% else %}{% url 'recipt:return_product' %}{% endif %}" method="post">
        {% csrf_token %}
        
        <!-- Dynamic heading based on whether you are editing or returning a product -->
        <h1>
            {% if is_editing %}
                Please edit product details
            {% else %}
                Please return product details
            {% endif %}
        </h1>

        <!-- Show the receipt code if not already set in session -->
        <h6>Here is the receipt code: {{ request.session.recipt_code_buy }}</h6>
        {% if not request.session.recipt_code_buy %}
            {{ form_recipt.as_p }}
        {% endif %}
        
        <!-- Display the product form -->
        {{ form_product.as_p }}

        <!-- Submit button -->
        <input type="submit" style="width: fit-content; height: fit-content; background-color: brown; color: white; padding: 5px; margin-top: 7px; border-radius: 2px; border: 1px solid rgb(0, 0, 0);">
    </form>

    <!-- Button to view the receipt -->
    <a href="{% url 'recipt:index' %}">
        <button style="width: fit-content; height: fit-content; background-color: brown; color: white; padding: 5px; margin-top: -25px; border-radius: 2px; border: 1px solid rgb(0, 0, 0); float: right;">
            Your receipt
        </button>
    </a>
</div>
{% endblock %}